---
- name: Remove VMs
  hosts: localhost
  tasks:
    - name: Delete the "{{ delete_ns }}" namespace
      kubernetes.core.k8s:
        name: "{{ delete_ns }}"
        kind: Namespace
        api_version: v1
        state: absent
    - name: Gather facts to include custom stats
      setup:
        filter: ansible_local
    - name: Debug custom stat
      debug:
        msg: "The value of my_stat is {{ ansible_local.my_stat }}"
